steps:
    - name: 'gcr.io/k8s-skaffold/pack'
      entrypoint: 'pack'
      args: ['build', '--builder=heroku/buildpacks', 'gcr.io/$PROJECT_ID/symfony-demo:$COMMIT_SHA']
    - name: 'docker'      
      args: ['tag', 'gcr.io/$PROJECT_ID/symfony-demo:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/symfony-demo:latest']    
images: 
  - 'gcr.io/$PROJECT_ID/symfony-demo'